challenge/models/auth.py
#coding: utf-8

from hashlib import sha1

from challenge.db import db

__all__ = ['Auth']


class Auth(db.Model):
    __tablename__ = 'auth'

    id = db.Column(db.Integer, primary_key=True)
    password = db.Column(db.String(64), nullable=False)

    def __init__(self, password):
        self.password = Auth.encrypt(password)

    def __str__(self):
        return '<Auth %d>' % (self.id)

    def __repr__(self):
        return self.__str__()

    @staticmethod
    def encrypt(raw):
        return sha1(raw).hexdigest()

challenge/models/record.py
#coding: utf-8

from sqlalchemy.orm import backref

from challenge.db import db

__all__ = ['Record']


class Record(db.Model):
    __tablename__ = 'record'

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(db.String(64), nullable=False)
    key = db.Column(db.String(64), nullable=False, unique=True)

    stage_id = db.Column(db.Integer, db.ForeignKey('stage.id'))
    stage = db.relationship('Stage')

    next_record_id = db.Column(db.Integer, db.ForeignKey('record.id'))
    # records are single linked list
    prev = db.relationship('Record', uselist=False, remote_side=[id],
                           backref=backref('next', uselist=False))

    def __init__(self, session_id, key, stage, prev=None):
        self.session_id = session_id
        self.key = key
        self.stage_id = stage.id
        self.prev = prev

    def __str__(self):
        return '<Record %s %s>' % (self.key, self.session_id)

    def __repr__(self):
        return self.__str__()

    @property
    def last(self):
        '''Get last record from the records chains'''
        node = self
        while node.next:
            node = node.next
        return node

    @property
    def first(self):
        '''Get first record from the records chains'''
        node = self
        while node.prev:
            node = node.prev
        return node

    @property
    def is_finish(self):
        return self.last.stage.next is None

challenge/backend/forms.py
#coding: utf-8

from flask_wtf import Form
from wtforms import PasswordField, TextField, SelectField
from wtforms.validators import DataRequired


class FakeObj(object):
    '''Fake a attr base object from dict'''

    def __init__(self, d):
        self._data = d

    def __getattr__(self, key):
        return self._data[key]


class AuthForm(Form):

    password = PasswordField('password', validators=[DataRequired()])


class UpdatePasswordForm(Form):

    orig_password = PasswordField('orig_password', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])


class QuizForm(Form):

    display_name = TextField('display_name', validators=[DataRequired()])
    quiz_name = TextField('quiz_name')
    prev_quiz = SelectField('prev_quiz', coerce=int,
                            validators=[DataRequired()])

    def prepare_prev_quiz(self, other_quizs, quiz=None):
        pair = lambda x: [(i.id, i.display_name) for i in x]
        not_me_and_children = (lambda me: lambda x: x.id != me.id and
                               x not in me.children)

        quiz = quiz or FakeObj({
            'id': 0,
            'children': []
        })

        self.prev_quiz.choices = pair(filter(not_me_and_children(quiz),
                                             other_quizs))

challenge/backend/__init__.py
#coding: utf-8

from app import *

challenge/backend/app.py
#coding: utf-8

import functools
import logging

from flask import Blueprint
from flask import request, redirect, url_for, render_template, session, flash

from challenge.db import db
from challenge.models import Auth, Stage, Record

from .forms import AuthForm, UpdatePasswordForm, QuizForm


__all__ = ['bp']


bp = Blueprint('backend', __name__, template_folder='templates',
               static_folder='static')
logger = logging.getLogger('app')


def auth_login():
    session['is_login'] = 'yes'


def auth_logout():
    session['is_login'] = 'no'


def is_login():
    return session.get('is_login') == 'yes'


def auth_require(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        if not is_login():
            flash('You must login first!', category='error')
            flash(request.url, category='next')
            return redirect(url_for('.auth'))
        return func(*args, **kwargs)
    return wrapper


@bp.route('/auth', methods=['GET', 'POST'])
def auth():
    form = AuthForm()
    if form.validate_on_submit():
        password = request.form.get('password')
        if not Auth.query.filter_by(password=Auth.encrypt(password)).first():
            flash('Password incorrect!', category='error')
            return redirect(url_for('.auth'))
        auth_login()
        return redirect(request.args.get('next') or url_for('.index'))
    return render_template('auth.html', form=form)


@bp.route('/out', methods=['GET'])
@auth_require
def logout():
    auth_logout()
    flash('Log out successfully, see you!', category='success')
    return redirect(url_for('.auth'))


@bp.route('/', methods=['GET'])
@auth_require
def index():
    return render_template('index.html')


@bp.route('/me', methods=['GET', 'POST'])
@auth_require
def me():
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        original = request.form.get('orig_password')
        password = request.form.get('password')
        user = Auth.query.filter_by(password=Auth.encrypt(original)).first()
        if user:
            user.password = Auth.encrypt(password)
            db.session.commit()
            auth_logout()
            flash('Password updated, please login again!', category='success')
            return redirect(url_for('.auth'))
        flash('Original password incorrect!', category='error')
        return redirect(url_for('.me'))
    return render_template('me.html', form=form)


@bp.route('/quizs', methods=['GET'])
@auth_require
def list_quizs():
    return render_template('quizs.html', quizs=Stage.query.all())


@bp.route('/quiz/<int:quiz_id>', methods=['GET', 'POST'])
@auth_require
def quiz(quiz_id):
    q = Stage.query.filter_by(id=quiz_id).first_or_404()
    form = QuizForm(obj=q)
    form.prepare_prev_quiz(Stage.query.all(), q)
    if form.validate_on_submit():
        display_name = request.form.get('display_name')
        prev_quiz_id = int(request.form.get('prev_quiz') or 0)
        prev_quiz = Stage.query.filter_by(id=prev_quiz_id).first()
        q.display_name = display_name
        q.prev = prev_quiz
        db.session.commit()
        flash('Quiz\'s informations updated!', category='success')
        return redirect(url_for('.quiz', quiz_id=quiz_id))
    return render_template('quiz.html', form=form, quiz=q)


@bp.route('/quiz/<int:quiz_id>/remove', methods=['GET'])
@auth_require
def remove_quiz(quiz_id):
    q = Stage.query.filter_by(id=quiz_id).first_or_404()
    flash('Quiz %s removed successfully!' % q.display_name, category='success')
    db.session.delete(q)
    db.session.commit()
    return redirect(url_for('.list_quizs'))


@bp.route('/quiz/create', methods=['GET', 'POST'])
@auth_require
def create_quiz():
    form = QuizForm()
    form.prepare_prev_quiz(Stage.query.all())
    if form.validate_on_submit():
        display_name = request.form.get('display_name')
        quiz_name = request.form.get('quiz_name')
        prev_quiz_id = int(request.form.get('prev_quiz') or 0)
        prev_quiz = Stage.query.filter_by(id=prev_quiz_id).first()
        q = Stage(display_name, quiz_name, prev_quiz)
        db.session.add(q)
        db.session.commit()
        logger.info('Created %s' % q)
        flash('Created new quiz %s' % display_name, category='success')
        return redirect(url_for('.list_quizs'))
    return render_template('quiz.create.html', form=form)


@bp.route('/records', methods=['GET'])
@auth_require
def list_records():
    records = list(set([record.last for record in Record.query.all()]))
    finish_records = filter(lambda x: x.is_finish, records)
    return render_template('records.html', records=records,
                           finish_records=finish_records)


@bp.route('/records/empty', methods=['GET'])
@auth_require
def empty_records():
    # TODO batch expresssion
    for record in Record.query.all():
        db.session.delete(record)
    db.session.commit()
    flash('All records were removed successfully!', category='success')
    return redirect(url_for('.list_records'))

challenge/quizs/__init__.py
#coding: utf-8

from .app import *

challenge/quizs/app.py
#coding: utf-8

import logging

from flask import current_app as app
from flask import Blueprint, session, render_template

from challenge.utils import key
from challenge.db import db
from challenge.models import Stage, Record

from .utils import load


__all__ = ['bp']


bp = Blueprint('quiz', __name__, template_folder='templates')
logger = logging.getLogger('app')


def generate_session_id():
    return key.generate(app.config['CHALLENGE_SESSION_KEY_LENGTH'])


def generate_key():
    return key.generate(app.config['CHALLENGE_KEY_LENGTH'])


def new_record(stage, session_id=None, prev=None):
    session_id = session_id or generate_session_id()
    while True:
        key = generate_key()
        # TODO use raw sql
        if not Record.query.filter_by(key=key).first():
            break
    record = Record(session_id=session_id, key=key, stage=stage, prev=prev)

    db.session.add(record)
    db.session.commit()

    logger.debug('created new %s' % record)
    return record


def retrieve_record(stage, session_id=None, prev=None):
    record = Record.query.filter_by(stage_id=stage.id,
                                    session_id=session_id).first()
    if not record:
        record = new_record(stage, session_id, prev)

    return record


@bp.errorhandler(404)
def not_your_key(error):
    return render_template('404.html'), 404


@bp.route('/', methods=['GET'])
@bp.route('/start', methods=['GET'])
def start():
    init_stage = app.config['CHALLENGE_FIRST_QUIZ']
    init = Stage.query.filter_by(**init_stage).first_or_404()
    record = new_record(init)
    session['session_id'] = record.session_id

    quiz = load(init.quiz_name)

    return quiz(record.key)


@bp.route('/<string:key>', methods=['GET'])
def quiz(key):
    session_id = session.get('session_id')
    query = {
        'session_id': session_id,
        'key': key
    }
    last_record = Record.query.filter_by(**query).first_or_404()

    if not last_record.stage.next:
        logger.info('%s has finished all quizs!' % session_id)
        return 'You have finished it! Congs!'

    record = retrieve_record(last_record.stage.next, session_id, last_record)
    quiz = load(record.stage.quiz_name)

    return quiz(record.key)

challenge/views/backend.py
#coding: utf-8

import functools
import logging

from flask import Blueprint
from flask import request, redirect, url_for, render_template, session, flash

from challenge.db import db
from challenge.models import Auth, Stage, Record


bp = Blueprint('backend', __name__, template_folder='../templates/backend',
               static_folder='static')
logger = logging.getLogger('app')


def auth_login():
    session['is_login'] = 'yes'


def auth_logout():
    session['is_login'] = 'no'


def is_login():
    return session.get('is_login') == 'yes'


def auth_require(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        if not is_login():
            flash('You must login first!', category='error')
            flash(request.url, category='next')
            return redirect(url_for('.auth'))
        return func(*args, **kwargs)
    return wrapper


@bp.route('/auth', methods=['GET', 'POST'])
def auth():
    if request.method == 'POST':
        password = request.form.get('password')
        if not Auth.query.filter_by(password=Auth.encrypt(password)).first():
            flash('Password incorrect!', category='error')
            return redirect(url_for('.auth'))
        auth_login()
        return redirect(request.args.get('next') or url_for('.index'))
    return render_template('auth.html')


@bp.route('/out', methods=['GET'])
@auth_require
def logout():
    auth_logout()
    flash('Log out successfully, see you!', category='success')
    return redirect(url_for('.auth'))


@bp.route('/', methods=['GET'])
@auth_require
def index():
    return render_template('index.html')


@bp.route('/me', methods=['GET', 'POST'])
@auth_require
def me():
    if request.method == 'POST':
        original = request.form.get('orig_password')
        password = request.form.get('password')
        user = Auth.query.filter_by(password=Auth.encrypt(original)).first()
        if user:
            user.password = Auth.encrypt(password)
            db.session.commit()
            auth_logout()
            flash('Password updated, please login again!', category='success')
            return redirect(url_for('.auth'))
        flash('Original password incorrect!', category='error')
        return redirect(url_for('.me'))
    return render_template('me.html')


@bp.route('/quizs', methods=['GET'])
@auth_require
def list_quizs():
    return render_template('quizs.html', quizs=Stage.query.all())


@bp.route('/quiz/<int:quiz_id>', methods=['GET', 'POST'])
@auth_require
def quiz(quiz_id):
    q = Stage.query.filter_by(id=quiz_id).first_or_404()
    if request.method == 'POST':
        # TODO
        # form validation & record validation
        display_name = request.form.get('display_name')
        prev_quiz_id = int(request.form.get('prev_quiz') or 0)
        prev_quiz = Stage.query.filter_by(id=prev_quiz_id).first()
        q.display_name = display_name
        q.prev = prev_quiz
        db.session.commit()
        flash('Quiz\'s informations updated!', category='success')
        return redirect(url_for('.quiz', quiz_id=quiz_id))
    return render_template('quiz.html', quiz=q, quizs=Stage.query.all())


@bp.route('/quiz/<int:quiz_id>/remove', methods=['GET'])
@auth_require
def remove_quiz(quiz_id):
    q = Stage.query.filter_by(id=quiz_id).first_or_404()
    flash('Quiz %s removed successfully!' % q.display_name, category='success')
    db.session.delete(q)
    db.session.commit()
    return redirect(url_for('.list_quizs'))


@bp.route('/quiz/create', methods=['GET', 'POST'])
@auth_require
def create_quiz():
    if request.method == 'POST':
        # TODO
        # form validation & record validation
        display_name = request.form.get('display_name')
        quiz_name = request.form.get('quiz_name')
        prev_quiz_id = int(request.form.get('prev_quiz') or 0)
        prev_quiz = Stage.query.filter_by(id=prev_quiz_id).first()
        q = Stage(display_name, quiz_name, prev_quiz)
        db.session.add(q)
        db.session.commit()
        logger.info('Created %s' % q)
        flash('Created new quiz %s' % display_name, category='success')
        return redirect(url_for('.list_quizs'))
    return render_template('quiz.create.html', quizs=Stage.query.all())


@bp.route('/records', methods=['GET'])
@auth_require
def list_records():
    records = list(set([record.last for record in Record.query.all()]))
    finish_records = filter(lambda x: x.is_finish, records)
    return render_template('records.html', records=records,
                           finish_records=finish_records)


@bp.route('/records/empty', methods=['GET'])
@auth_require
def empty_records():
    # TODO batch expresssion
    for record in Record.query.all():
        db.session.delete(record)
    db.session.commit()
    flash('All records were removed successfully!', category='success')
    return redirect(url_for('.list_records'))

challenge/views/quiz.py
#coding: utf-8

import logging

from flask import current_app as app
from flask import Blueprint, session, render_template

from challenge.utils import key
from challenge.quizs import load
from challenge.db import db
from challenge.models import Stage, Record


bp = Blueprint('quiz', __name__, template_folder='templates')
logger = logging.getLogger('app')


def generate_session_id():
    return key.generate(app.config['CHALLENGE_SESSION_KEY_LENGTH'])


def generate_key():
    return key.generate(app.config['CHALLENGE_KEY_LENGTH'])


def new_record(stage, session_id=None, prev=None):
    session_id = session_id or generate_session_id()
    while True:
        key = generate_key()
        # TODO use raw sql
        if not Record.query.filter_by(key=key).first():
            break
    record = Record(session_id=session_id, key=key, stage=stage, prev=prev)

    db.session.add(record)
    db.session.commit()

    logger.debug('created new %s' % record)
    return record


def retrieve_record(stage, session_id=None, prev=None):
    record = Record.query.filter_by(stage_id=stage.id,
                                    session_id=session_id).first()
    if not record:
        record = new_record(stage, session_id, prev)

    return record


@bp.errorhandler(404)
def not_your_key(error):
    return render_template('404.html'), 404


@bp.route('/', methods=['GET'])
@bp.route('/start', methods=['GET'])
def start():
    init_stage = app.config['CHALLENGE_FIRST_QUIZ']
    init = Stage.query.filter_by(**init_stage).first_or_404()
    record = new_record(init)
    session['session_id'] = record.session_id

    quiz = load(init.quiz_name)

    return quiz(record.key)


@bp.route('/<string:key>', methods=['GET'])
def quiz(key):
    session_id = session.get('session_id')
    query = {
        'session_id': session_id,
        'key': key
    }
    last_record = Record.query.filter_by(**query).first_or_404()

    if not last_record.stage.next:
        logger.info('%s has finished all quizs!' % session_id)
        return 'You have finished it! Congs!'

    record = retrieve_record(last_record.stage.next, session_id, last_record)
    quiz = load(record.stage.quiz_name)

    return quiz(record.key)

challenge/backend/templates/auth.html
{% extends 'layout.html' %}

{% block container %}
    <section class="container medium">
        <div class="wrapper" id="login">
            {% include 'parts/alert.html' %}
            <div class="grid">
                <header>
                    <h1>Welcome Back</h1>
                </header>
                {% with next = get_flashed_messages(category_filter=['next']) %}
                <form action="{{ url_for('backend.auth', next=next or '') }}" method="post" class="pure-form pure-form-aligned">
                    {{ form.hidden_tag() }}
                    <div class="pure-control-group">
                        {{ form.password.label('Password:') }}
                        {{ form.password(class_='pure-u-1-2') }}
                    </div>
                    <div class="pure-controls">
                        <button class="pure-button pure-button-primary" type="submit">Sign in</button>
                    </div>
                </form>
                {% endwith %}
            </div>
        </div>
    </section>
{% endblock %}

challenge/backend/templates/index.html
{% extends 'module.html' %}

{% block module_content %}
<ul class="badges">
    <li><a class="badge" href="{{ url_for('backend.list_quizs') }}">Quizs</a></li>
    <li><a class="badge" href="{{ url_for('backend.list_records') }}">Records</a></li>
</ul>
{% endblock %}

challenge/backend/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Challenge{% endblock %}</title>
    {% block head %}
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('backend.static', filename='styles/vendor/pure-min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('backend.static', filename='styles/style.css') }}" />
    {% endblock %}
</head>
<body>
    {% block container %}
    {% endblock %}
</body>
{% block scripts %}
<script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>
<script src="{{ url_for('backend.static', filename='scripts/vinko.js') }}"></script>
{% endblock %}
</html>

challenge/backend/templates/me.html
{% extends 'module.html' %}

{% block module_content %}
<form action="{{ url_for('backend.me') }}" method="post" class="pure-form pure-form-stacked">
    {{ form.hidden_tag() }}
    <div class="pure-control-group">
        {{ form.orig_password.label('Password') }}
        {{ form.orig_password() }}
    </div>
    <div class="pure-control-group">
        {{ form.password.label('New Password') }}
        {{ form.password() }}
    </div>
    <div class="pure-controls">
        <button class="pure-button pure-button-primary" type="submit">Change password</button>
    </div>
</form>
{% endblock %}

challenge/backend/templates/module.html
{% extends 'layout.html' %}

{% block container %}
<section class="container">
    {% include 'parts/head.html' %}
    {% include 'parts/alert.html' %}
    <section id="dashboard" class="pure-g grid">
        <section id="main" class="pure-u-3-4">
            <header id="module-name">
                {% block module_name %}{% endblock %}
            </header>
            <article id="module-content">
                {% block module_content %}{% endblock %}
            </article>
        </section>
        {% include 'parts/side_nav.html' %}
    </section>
    {% include 'parts/footer.html' %}
</section>
{% endblock %}

challenge/backend/templates/quiz.create.html
{% set current = 'quiz' %}

{% extends 'module.html' %}

{% block module_name %}
<h1>Create New Quiz</h1>
{% endblock %}

{% block module_content %}
<form action="{{ url_for('backend.create_quiz') }}" method="post" class="pure-form pure-form-stacked">
    {{ form.hidden_tag() }}
    <div class="pure-control-group">
        {{ form.display_name.label('Name:') }}
        {{ form.display_name }}
    </div>
    <div class="pure-control-group">
        {{ form.quiz_name.label('Module:')}}
        {{ form.quiz_name }}
    </div>
    <div class="pure-control-group">
        {{ form.prev_quiz.label('Prev Quiz:') }}
        {{ form.prev_quiz }}
    </div>
    <div class="pure-controls">
        <button class="pure-button pure-button-primary" type="submit">Create</button>
    </div>
</form>
{% endblock %}

challenge/backend/templates/quiz.html
{% set current = 'quiz' %}

{% extends 'module.html' %}

{% block module_name %}
<h1>Quiz: {{ quiz.display_name }}</h1>
{% endblock %}

{% block module_content %}
<form action="{{ url_for('backend.quiz', quiz_id=quiz.id) }}" method="post" class="pure-form pure-form-stacked">
    {{ form.hidden_tag() }}
    <div class="pure-control-group">
        {{ form.display_name.label('Name:') }}
        {{ form.display_name }}
    </div>
    <div class="pure-control-group">
        {{ form.quiz_name.label('Module:')}}
        {{ form.quiz_name(readonly=true) }}
    </div>
    <div class="pure-control-group">
        {{ form.prev_quiz.label('Prev Quiz:') }}
        {{ form.prev_quiz }}
    </div>
    {% if quiz.next.quiz_name %}
    <div class="pure-control-group">
        <label for="next_quiz">Next Quiz:</label>
        <a href="{{ url_for('backend.quiz', quiz_id=quiz.next.id) }}">{{ quiz.next.quiz_name }}</a>
    </div>
    {% endif %}
    <div class="pure-controls">
        <button class="pure-button pure-button-primary" type="submit">Updated informations</button>
    </div>
</form>
{% endblock %}

challenge/backend/templates/quizs.html
{% set current = 'quiz' %}

{% extends 'module.html' %}

{% block module_name %}
<h1>All Quizs</h1>
{% endblock %}

{% block module_content %}
<div class="inner pure-g">
    <div id="module-meta" class="pure-u-2-3">
        <p>Total: {{ quizs | length }}</p>
    </div>
    <section id="module-op" class="pure-u-1-3">
        <a class="pure-button pure-button-success pull-right" href="{{ url_for('backend.create_quiz') }}">Add a quiz</a>
    </section>
</div>
{% if quizs %}
<table class="list pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>Name</th>
            <th>Module Name</th>
            <th>OP.</th>
        </tr>
    </thead>
{% for quiz in quizs %}
    <tr>
        <td><a href="{{ url_for('backend.quiz', quiz_id=quiz.id) }}">{{ quiz.display_name }}</a></td>
        <td>{{ quiz.quiz_name }}</td>
        <td><a href="{{ url_for('backend.remove_quiz', quiz_id=quiz.id) }}" class="pure-button pure-button-error">Remove</a></td>
    </tr>
{% endfor %}
</table>
{% endif %}
{% endblock %}

challenge/backend/templates/records.html
{% set current = 'record' %}

{% extends 'module.html' %}

{% block module_name %}
<h1>All Records</h1>
{% endblock %}

{% block module_content %}
<div class="inner pure-g">
    <div class="module-meta pure-u-2-3">
        <p>Total: {{ records | length }} | Finished: {{ finish_records | length }}</p>
    </div>
    {% if records %}
    <section id="module-op" class="pure-u-1-3">
        <a class="pure-button pure-button-error pull-right" href="{{ url_for('backend.empty_records') }}">Empty records</a>
    </section>
    {% endif %}
</div>
{% if finish_records %}
<table class="list pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>Finished Session Id</th>
        </tr>
    </thead>
    {% for record in finish_records %}
    <tr>
        <td>{{ record.session_id }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if records %}
<table class="list pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>Session Id</th>
            <th>Current Stage</th>
            <th>Finished?</th>
        </tr>
    </thead>
    {% for record in records %}
    <tr>
        <td>{{ record.session_id }}</td>
        <td><a href="{{ url_for('backend.quiz', quiz_id=record.stage.id) }}">{{ record.stage.display_name }}</a></td>
        <td>{% if record.is_finish %} Yes! {% else %} Nope {% endif %}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}